# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import img_blur_detected_pb2 as img__blur__detected__pb2


class img_blur_detectedStub(object):
    """写服务
    服务名
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.blur_detect = channel.unary_unary(
                '/blur_detected.img_blur_detected/blur_detect',
                request_serializer=img__blur__detected__pb2.img_gray_request.SerializeToString,
                response_deserializer=img__blur__detected__pb2.score_reply.FromString,
                )


class img_blur_detectedServicer(object):
    """写服务
    服务名
    """

    def blur_detect(self, request, context):
        """定义接口和数据类型  hello_hu 函数名
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_img_blur_detectedServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'blur_detect': grpc.unary_unary_rpc_method_handler(
                    servicer.blur_detect,
                    request_deserializer=img__blur__detected__pb2.img_gray_request.FromString,
                    response_serializer=img__blur__detected__pb2.score_reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blur_detected.img_blur_detected', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class img_blur_detected(object):
    """写服务
    服务名
    """

    @staticmethod
    def blur_detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blur_detected.img_blur_detected/blur_detect',
            img__blur__detected__pb2.img_gray_request.SerializeToString,
            img__blur__detected__pb2.score_reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
