# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: img_blur_detected.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='img_blur_detected.proto',
  package='blur_detected',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17img_blur_detected.proto\x12\rblur_detected\"$\n\x10img_gray_request\x12\x10\n\x08img_gray\x18\x01 \x01(\x0c\"\x1c\n\x0bscore_reply\x12\r\n\x05score\x18\x01 \x01(\t2a\n\x11img_blur_detected\x12L\n\x0b\x62lur_detect\x12\x1f.blur_detected.img_gray_request\x1a\x1a.blur_detected.score_reply\"\x00\x62\x06proto3'
)




_IMG_GRAY_REQUEST = _descriptor.Descriptor(
  name='img_gray_request',
  full_name='blur_detected.img_gray_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img_gray', full_name='blur_detected.img_gray_request.img_gray', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=78,
)


_SCORE_REPLY = _descriptor.Descriptor(
  name='score_reply',
  full_name='blur_detected.score_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='blur_detected.score_reply.score', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['img_gray_request'] = _IMG_GRAY_REQUEST
DESCRIPTOR.message_types_by_name['score_reply'] = _SCORE_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

img_gray_request = _reflection.GeneratedProtocolMessageType('img_gray_request', (_message.Message,), {
  'DESCRIPTOR' : _IMG_GRAY_REQUEST,
  '__module__' : 'img_blur_detected_pb2'
  # @@protoc_insertion_point(class_scope:blur_detected.img_gray_request)
  })
_sym_db.RegisterMessage(img_gray_request)

score_reply = _reflection.GeneratedProtocolMessageType('score_reply', (_message.Message,), {
  'DESCRIPTOR' : _SCORE_REPLY,
  '__module__' : 'img_blur_detected_pb2'
  # @@protoc_insertion_point(class_scope:blur_detected.score_reply)
  })
_sym_db.RegisterMessage(score_reply)



_IMG_BLUR_DETECTED = _descriptor.ServiceDescriptor(
  name='img_blur_detected',
  full_name='blur_detected.img_blur_detected',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=110,
  serialized_end=207,
  methods=[
  _descriptor.MethodDescriptor(
    name='blur_detect',
    full_name='blur_detected.img_blur_detected.blur_detect',
    index=0,
    containing_service=None,
    input_type=_IMG_GRAY_REQUEST,
    output_type=_SCORE_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMG_BLUR_DETECTED)

DESCRIPTOR.services_by_name['img_blur_detected'] = _IMG_BLUR_DETECTED

# @@protoc_insertion_point(module_scope)
