# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hello_pb2 as hello__pb2


class Say_helloStub(object):
    """写服务
    服务名
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.hello_hu = channel.unary_unary(
                '/test.Say_hello/hello_hu',
                request_serializer=hello__pb2.hello_hu_request.SerializeToString,
                response_deserializer=hello__pb2.hello_hu_reply.FromString,
                )


class Say_helloServicer(object):
    """写服务
    服务名
    """

    def hello_hu(self, request, context):
        """定义接口和数据类型  hello_hu 函数名
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Say_helloServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'hello_hu': grpc.unary_unary_rpc_method_handler(
                    servicer.hello_hu,
                    request_deserializer=hello__pb2.hello_hu_request.FromString,
                    response_serializer=hello__pb2.hello_hu_reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.Say_hello', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Say_hello(object):
    """写服务
    服务名
    """

    @staticmethod
    def hello_hu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.Say_hello/hello_hu',
            hello__pb2.hello_hu_request.SerializeToString,
            hello__pb2.hello_hu_reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
